name: SkyWars
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 1.0.0
main: skywars\SkyWars
author: GamakCZ
description: SkyWars minigame plugin
website: https://github.com/GamakCZ/SkyWars

permissions:
  sw.cmd:
    description: Permission to all SkyWars commands
    default: op
    children:
      sw.cmd.help:
        description: Permission for /sw help
        default: op
      sw.cmd.create:
        description: Permission for /sw create
        default: op
      sw.cmd.set:
        description: Permission for /sw set
        default: op
      sw.cmd.arenas:
        description: Permission for /sw arenas
        default: op